workflows:
  android-workflow:
    name: Android LaTaxi Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "in.techware.lataxi"
      java: 11
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Get Gradle version
        script: | 
          ./gradlew --version
      - name: Build Android APK
        script: | 
          UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          ./gradlew assembleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-passenger-workflow:
    name: Android Passenger App Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "in.techware.lataxipassenger"
      java: 11
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Get Gradle version
        script: | 
          ./gradlew --version
      - name: Build Android APK
        script: | 
          UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          ./gradlew assembleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-debug:
    name: Android Debug Build (Fast)
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 11
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build debug APK
        script: | 
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
